### ISSUE TITLE
What is the difference between this plugin and using `eslint no-restricted-syntax`?

### ISSUE THREAD

**Issue by GermanJablo** [nene/eslint-plugin-no-null#5]
I found in [this Eslint discussion](https://github.com/eslint/eslint/issues/12177) that you can prevent the use of null using this plugin, or by using `eslint no-restricted-syntax`:

```json
{
    "rules": {
        "no-restricted-syntax": [
            "error",
            {
                "selector": "Literal[raw='null']",
                "message": "Use undefined instead of null"
            }
        ]
    }
}

```

Am I going to find any difference between using this plugin or that rule, or are they effectively the same?

**Comment by nene** [comment]
I think there effectively is no difference.

IIRC, when I created this plugin the `no-restricted-syntax` rule did not allow for such fancy selectors (one could only ban all `Literal` nodes, but not a specific type of literal). Otherwise I would have simply used the `no-restricted-syntax` rule and not created this plugin.

**Comment by GermanJablo** [comment]
Good to know. Thank you very much!
